### ISSUE TITLE
Error on Windows installation pact-mock-service.rb:1:in `require': cannot load such file -- pact/mock_service/cli (LoadError)

### ISSUE THREAD

**Issue by ShvetsovZE** [pact-foundation/pact-ruby-standalone#76]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Upgraded to the latest version of the relevant libraries
* [x] Checked to see if the issue has already been raised
* [ ] Created an executable example that demonstrates the issue using either:
  * a Dockerfile
  * a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
  * a Git repository with a Travis or Appveyor (or similar) build
  * a gist with all the relevant code and full instructions on how to run it

## Software versions

* **pact-ruby-standalone:** eg pact-1.88.89
* **OS**: e.g. Windows 10 Enterprise Build number 19044.1706

## Expected behavior

Pact standalone executables are being installed via CMD after following the Windows installation guide and in particular, running ` .\bin\pact-mock-service.bat --help start`

## Actual behaviour
pact-mock-service.bat throws a following error from ruby file 
C:\tools\pact>.\bin\pact-mock-service.bat --help start
C:/tools/pact/lib/app/pact-mock-service.rb:1:in `require': cannot load such file -- pact/mock_service/cli (LoadError)
        from C:/tools/pact/lib/app/pact-mock-service.rb:1:in `<main>'

## Steps to reproduce

Simply follow the Windows installation guide 

> Download package, unzip, then run:
> $ cd pact
> $ .\bin\pact-mock-service.bat --help start
> $ .\bin\pact-provider-verifier.bat --help verify

## Side notes
We tested it with colleague on Mac OS and it works perfectly fine

**Comment by bethesque** [comment]
I'm a bit confused by this one. @uglyog can reproduce the issue on his machine.


```
C:\Users\ron\Downloads\pact-1.88.89-win32\pact>bin\pact.bat
C:/Users/ron/Downloads/pact-1.88.89-win32/pact/lib/app/pact.rb:1:in `require': cannot load such file -- pact/cli (LoadError)
        from C:/Users/ron/Downloads/pact-1.88.89-win32/pact/lib/app/pact.rb:1:in `<main>'
```

I am not a windows user, but my husband is in the office today so I fumbled around with his windows machine and managed to run it without any issues at all.

![20220527_110002](https://user-images.githubusercontent.com/446228/170608299-ba364068-7833-48a8-9d0a-75f59b3e9771.jpg)

**Comment by bethesque** [comment]
Link to problem file: https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.89/pact-1.88.89-win32.zip

**Comment by bethesque** [comment]
Given that the code is the same, it seems like it must be some kind of environmental issue, the most likely cause being an environment variable that's affecting the load path somehow.

**Comment by Inksprout** [comment]
I haven't been able to reproduce this on my windows machine
![279933029_414493093865422_4007159061801292260_n](https://user-images.githubusercontent.com/13867336/170644010-ae456024-0bda-44b6-97fb-1a95fa126c3b.png)
windows version: 

Edition	Windows 10 Home
Version	21H1
Installed on	‎10/‎08/‎2020
OS build	19043.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by YOU54F** [comment]
Just tested against GitHub's two windows runners and all good 🤷🏾‍♂️ - Will fire up my windows 10 desktop and try shortly

windows-2019 - https://github.com/YOU54F/pact-standalone-windows-test/runs/6624009271?check_suite_focus=true#step:3:2731
windows-latest - https://github.com/YOU54F/pact-standalone-windows-test/runs/6624009212?check_suite_focus=true#step:3:2731

```

   
name: test standalone

on:
  workflow_dispatch:

jobs:


  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest,windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: test standalone against ${{ matrix.os }}
        run: |
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.89/pact-1.88.89-win32.zip
          unzip pact-1.88.89-win32.zip
          cd pact
          ./bin/pact-mock-service --help start
          ./bin/pact-provider-verifier --help verify
```
